#!/bin/sh
# Pushes this directory to the server and runs scripts/*.sh against it in order.
# Usage: ./deploy.sh [host] [key_path]
# With no args, reads HOST/KEY from .env (generated by `terraform apply`, gitignored).
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

if [ -f "$SCRIPT_DIR/.env" ]; then
  # shellcheck disable=SC1091
  . "$SCRIPT_DIR/.env"
fi

HOST="${1:-${HOST:-}}"
KEY="${2:-${KEY:-}}"

if [ -z "$HOST" ]; then
  echo "usage: $0 <host-or-ip> [key_path]  (or run terraform apply first to generate .env)" >&2
  exit 1
fi
KEY="${KEY:-$HOME/.ssh/id_ed25519}"

SSH="ssh -i $KEY -o StrictHostKeyChecking=accept-new"
REMOTE_DIR=/root/temperingworks-provision

echo "==> pushing provision/ to root@${HOST}:${REMOTE_DIR}"
ssh -i "$KEY" -o StrictHostKeyChecking=accept-new "root@${HOST}" "mkdir -p ${REMOTE_DIR}"
scp -i "$KEY" -o StrictHostKeyChecking=accept-new -r "$SCRIPT_DIR/files" "$SCRIPT_DIR/scripts" "root@${HOST}:${REMOTE_DIR}/"

for step in "$SCRIPT_DIR"/scripts/*.sh; do
  name="$(basename "$step")"
  echo "==> running $name"
  $SSH "root@${HOST}" "chmod +x ${REMOTE_DIR}/scripts/${name} && ${REMOTE_DIR}/scripts/${name}"
done

echo "==> done. Once you have a build: ./deploy-app.sh <binary> <frontend-dist-dir>"
