#!/bin/sh
# Syncs a locally-built binary + frontend static assets to the server and (re)starts the
# service. Usage: ./deploy-app.sh <local-binary-path> <local-frontend-dist-dir> [host] [key_path]
# With no host/key, reads HOST/KEY from .env (generated by `terraform apply`, gitignored).
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

if [ -f "$SCRIPT_DIR/.env" ]; then
  # shellcheck disable=SC1091
  . "$SCRIPT_DIR/.env"
fi

BIN="${1:?usage: $0 <local-binary-path> <local-frontend-dist-dir> [host] [key_path]}"
DIST="${2:?missing local frontend dist dir}"
HOST="${3:-${HOST:-}}"
KEY="${4:-${KEY:-}}"

[ -n "$HOST" ] || { echo "no host given and no .env found — run terraform apply first, or pass one" >&2; exit 1; }
KEY="${KEY:-$HOME/.ssh/id_ed25519}"

SSH="ssh -i $KEY -o StrictHostKeyChecking=accept-new"

rsync -az -e "$SSH" "$BIN" "root@${HOST}:/opt/temperingworks/bin/temperingworks-server"
rsync -az --delete -e "$SSH" "$DIST/" "root@${HOST}:/opt/temperingworks/static/"

$SSH "root@${HOST}" '
  chown temperingworks:temperingworks /opt/temperingworks/bin/temperingworks-server
  chmod 755 /opt/temperingworks/bin/temperingworks-server
  rc-service temperingworks-server status >/dev/null 2>&1 \
    && rc-service temperingworks-server restart \
    || rc-service temperingworks-server start
'
