#!/bin/sh
# Provisions the temperingworks Alpine server in one pass: base packages, sshd
# hardening, C10K sysctl tuning, C++ toolchain, log rotation, and the app's OpenRC
# service. Runs entirely over SSH as root — Alpine's cloud AMIs ship without sudo/doas,
# so ../terraform/compute.tf sets root's own SSH key directly via user_data.
#
# Usage: ./deploy.sh [host] [key_path]
# With no args, reads HOST/KEY from .env (generated by `terraform apply`, gitignored).
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  # shellcheck disable=SC1091
  . "$SCRIPT_DIR/.env"
fi

HOST="${1:-${HOST:-}}"
KEY="${2:-${KEY:-}}"
if [ -z "$HOST" ]; then
  echo "usage: $0 <host-or-ip> [key_path]  (or run terraform apply first to generate .env)" >&2
  exit 1
fi
KEY="${KEY:-$HOME/.ssh/id_ed25519}"

ssh -i "$KEY" -o StrictHostKeyChecking=accept-new "root@${HOST}" 'sh -s' <<'REMOTE'
set -eu

# ---- base packages, timezone, app user/group ----
apk update
apk upgrade
apk add --no-cache curl vim htop tzdata build-base cmake git logrotate dcron rsync

ln -sf /usr/share/zoneinfo/UTC /etc/localtime

getent group temperingworks >/dev/null 2>&1 || addgroup -S temperingworks
id -u temperingworks >/dev/null 2>&1 || adduser -S -D -H -s /sbin/nologin -G temperingworks temperingworks

# ---- swapfile: t4g.small has 2GB RAM, on-box `make -j$(nproc)` builds can spike it,
# and Alpine provisions no swap by default ----
if [ ! -f /swapfile ]; then
  dd if=/dev/zero of=/swapfile bs=1M count=1024
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ---- sshd hardening: key-only auth; root allowed only via key, never a password ----
cat > /etc/ssh/sshd_config <<'EOF'
Port 22
AddressFamily any
ListenAddress 0.0.0.0

HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
AuthorizedKeysFile .ssh/authorized_keys

X11Forwarding no
AllowAgentForwarding yes
AllowTcpForwarding yes
PrintMotd no
ClientAliveInterval 60
ClientAliveCountMax 3

SyslogFacility AUTH
LogLevel INFO

Subsystem sftp /usr/lib/ssh/sftp-server
EOF
sshd -t
rc-service sshd restart

# ---- C10K sysctl tuning for a high-concurrency epoll TCP/HTTP server ----
# tcp_tw_recycle deliberately omitted — removed in kernel 4.12+.
cat > /etc/sysctl.d/99-temperingworks-c10k.conf <<'EOF'
fs.file-max = 2097152
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65535
net.ipv4.tcp_max_syn_backlog = 65535
net.ipv4.tcp_syncookies = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
EOF
sysctl --system

# ---- logrotate + dcron: Alpine ships neither by default, and the server writes its
# own log files directly rather than syslog ----
rc-update add dcron
rc-service dcron start

cat > /etc/logrotate.d/temperingworks-server <<'EOF'
/opt/temperingworks/logs/*.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    copytruncate
}
EOF

# ---- app service: directory layout + OpenRC unit ----
mkdir -p /opt/temperingworks/bin /opt/temperingworks/static /opt/temperingworks/logs
chown -R temperingworks:temperingworks /opt/temperingworks

cat > /etc/init.d/temperingworks-server <<'EOF'
#!/sbin/openrc-run
name="temperingworks-server"
description="temperingworks C++ C10K web/TCP server"
command="/opt/temperingworks/bin/temperingworks-server"
command_args="--port ${APP_PORT} --static-dir /opt/temperingworks/static"
command_background=true
command_user="temperingworks:temperingworks"
pidfile="/run/${RC_SVCNAME}.pid"
output_log="/opt/temperingworks/logs/temperingworks-server.log"
error_log="/opt/temperingworks/logs/temperingworks-server.error.log"

depend() {
    need net
    after firewall
}
EOF
chmod 755 /etc/init.d/temperingworks-server

# rc_ulimit is OpenRC's no-PAM mechanism for per-service ulimits (Alpine ships without
# linux-pam) — this filename must exactly match /etc/init.d/temperingworks-server.
cat > /etc/conf.d/temperingworks-server <<'EOF'
rc_ulimit="-n 65535"
APP_PORT=8080
EOF

rc-update add temperingworks-server default

# Left enabled but stopped (not failed) until deploy-app.sh syncs a real binary.
if [ -x /opt/temperingworks/bin/temperingworks-server ]; then
  rc-service temperingworks-server start
else
  echo "No binary yet at /opt/temperingworks/bin/temperingworks-server — service enabled but not started."
  echo "Run ./deploy-app.sh once you have a build."
fi
REMOTE

echo "==> done. Once you have a build: ./deploy-app.sh <binary> <frontend-dist-dir>"
